// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

const isTest = process.env.NODE_ENV === "test";

config({
  path: isTest ? ".env.test" : ".env",
  override: false,
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
